name: Android

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-rust:
    name: Build Binaries
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - build: android-arm
            target-triple: armv7-linux-androideabi
            target-simple: armeabi-v7a

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target-triple }}

      - name: Install cargo-ndk
        run: |
          cargo install cargo-ndk

      - name: Build project
        run: |
          cd rust
          cargo ndk -t ${{ matrix.target-simple }} build --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./*
