name: Android

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-rust:
    name: Build Binaries
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - build: android-arm
            target-triple: armv7-linux-androideabi
            target-simple: armeabi-v7a

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install ${{ matrix.target-triple }} toolchains
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target-triple }}

      - name: Install cargo-ndk & the toolchain (again)
        run: |
          cargo install cargo-ndk
          rustup target install ${{ matrix.target-triple }}

      - name: Build project
        run: |
          export TOOLCHAIN=$ANDROID_NDK/build/cmake/android.toolchain.cmake

          cd rust
          cargo ndk -t ${{ matrix.target-simple }} build --release -- -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN -DANDROID_ABI=armeabi-v7a

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./*
